FROM public.ecr.aws/lambda/python:3.12

# Copy function code
COPY app.py ${LAMBDA_TASK_ROOT}
COPY saved_model ${LAMBDA_TASK_ROOT}
COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install --user -r requirements.txt

# Set the CMD to your lambda_handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "app.lambda_handler" ]
