# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY app.py /app
COPY saved_model /app
COPY requirements.txt /app

# Install the Python dependencies
RUN pip install -r requirements.txt
# RUN pip install flask

# Expose port 8080
EXPOSE 8080

# Run the application
CMD ["python", "app.py"]
